steps:
  # 🔧 Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Backend
    dir: 'app'
    args:
      - build
      - '-t'
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/ticketease/backend:latest'
      - '.'
    secretEnv:
      - SECRET_KEY
      - AUTH_ALGORITHM
      - SUPABASE_DB_URL

  # 🚚 Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'asia-east1-docker.pkg.dev/$PROJECT_ID/ticketease/backend:latest'

  # 🚀 Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - ticketease-backend-prod
      - '--image=asia-east1-docker.pkg.dev/$PROJECT_ID/ticketease/backend:latest'
      - '--region=asia-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    env:
      - 'SECRET_KEY'
      - 'AUTH_ALGORITHM'
      - 'SUPABASE_DB_URL'
      - 'API_URL'

availableSecrets:
  secretManager:
    env:
      - key: SECRET_KEY
        versionName: projects/$PROJECT_ID/secrets/SECRET_KEY/versions/latest
      - key: AUTH_ALGORITHM
        versionName: projects/$PROJECT_ID/secrets/AUTH_ALGORITHM/versions/latest
      - key: SUPABASE_DB_URL
        versionName: projects/$PROJECT_ID/secrets/SUPABASE_DB_URL/versions/latest

substitutions:
  _API_URL: "https://ticketease-frontend-staging-396633212684.asia-east1.run.app/"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
